brew "bash"
brew "bash-completion"
brew "curl"
brew "gh"
brew "git"
brew "lazygit"
brew "neovim"
brew "node@16"
brew "ripgrep"
brew "tmux"
brew "watchman"

cask "docker"
cask "dropbox"
cask "gpg-suite-no-mail"
cask "keepingyouawake"
cask "rectangle"
cask "textmate"
